### ISSUE TITLE
Opening the HomePage after deleting a mod cause a error idk why tho 

### ISSUE THREAD

**Issue by MohammedGamer85** [MohammedGamer85/Mythic#59]

**Comment by Ikethepro18** [comment]
I'd assume with the circumstance the app must be checking for something that is no longer there, what's the error message exactly?

**Comment by MohammedGamer85** [comment]
@Ikethepro18 
![image](https://github.com/MohammedGamer85/Mythic/assets/100155245/00cd14d9-9e41-400a-b3c3-8481468c6523)
this is the condition and the problem is the funcation is given a id that is out of index. the reason idk how to fix this is because i can't figure out what is giving it this invaild command as this funcatin can be ran through xml. so all my debug tools just stop working.

**Comment by MohammedGamer85** [comment]
YES i was right just needed to add support for reloading the xml and now it works
